env:
  browser: true
  es6: true
  node: true
parser: babel-eslint
plugins:
  - flowtype
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
rules:
  indent:
    - warn
    - 2
  quotes:
    - warn
    - single
  semi:
    - error
    - never
  comma-dangle:
    - off
